class CheckoutLocators:
    EXISTING_ACCOUNT_BUTTON = '//a[@class="showlogin"]'
    USERNAME_INPUT = 'username'
    PASSWORD_INPUT = 'password'
    LOGIN_BUTTON = 'login'
    BILLING_EMAIL_INPUT = 'billing_email'
    BANNER = 'woocommerce-store-notice'
    PAYMENT_FRAME = 'iframe[title="Bezpieczne pole wprowadzania płatności"]'
    CARD_NUMBER_INPUT = 'Field-numberInput'
    CARD_NUMBER_ERROR_MESSAGE = 'Field-numberError'
    CARD_EXPIRY_DATE_INPUT = 'Field-expiryInput'
    CARD_EXPIRY_DATE_ERROR_MESSAGE = 'Field-expiryError'
    CARD_CVC_CODE_INPUT = 'Field-cvcInput'
    CARD_CVC_CODE_ERROR_MESSAGE = 'Field-cvcError'
    TERMS_CHECKBOX = 'terms'
    PLACE_ORDER_BUTTON = 'place_order'
    CHECKBOX_ERROR_MESSAGE = 'li[data-id="terms"]'
